remote_theme              : "mmistakes/minimal-mistakes"
minimal_mistakes_skin     : "air"

title                     : "Machine Learning"
title_separator           : "-"
name                      : "Christopher Küster"
baseurl                   : "" # the subpath of your site, e.g. "/blog"
repository                : "chkbs/chkbs.github.io"


# Site Author
author:
  name                    : "Christopher Küster"
  avatar                  : "profile.png"
  bio                     : "Your biography for the left-hand sidebar"
  location                : "Munich"
  employer                :



include:
  - .htaccess
  - _pages
  - files


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
author_profile: true
