remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dirt"

title                    : "Machine Learning"
title_separator          : "-"
name                     : "Christopher Küster"
baseurl                  : "/" # the subpath of your site, e.g. "/blog"
